version: "3.2"
services:
    main:
      build: ./
      image: survey-form-v2:latest
      restart: always
      command: npm start
      volumes:
        - /c/Users/Administrator/AppData/Local/Jenkins/.jenkins/workspace/survey-form-v2_feature-abc/src:/var/www/app/src
        - /c/Users/Administrator/AppData/Local/Jenkins/.jenkins/workspace/survey-form-v2_feature-abc/package.json:/var/www/app/package.json
      ports:
        - 3000:3000
        - 9229:9229